"""Evidence-oriented numerical mathematics primitives."""
from .core import (
    numerical_root,
    numerical_nonlinear_system,
    numerical_derivative,
    numerical_integral,
    interpolate_linear,
    minimize_scalar,
    numerical_linear_solve,
    eigenproblem,
    condition_number,
    sensitivity_finite_difference,
    propagate_uncertainty,
    convergence_evidence,
    numerical_pde_1d_dirichlet,
    fft,
    monte_carlo_mean,
    parameter_sweep,
)
__all__ = [
    "numerical_root",
    "numerical_nonlinear_system",
    "numerical_derivative",
    "numerical_integral",
    "interpolate_linear",
    "minimize_scalar",
    "numerical_linear_solve",
    "eigenproblem",
    "condition_number",
    "sensitivity_finite_difference",
    "propagate_uncertainty",
    "convergence_evidence",
    "numerical_pde_1d_dirichlet",
    "fft",
    "monte_carlo_mean",
    "parameter_sweep",
]
