"""Independent-result verification for translated canonical Tensor IR.

The comparison target is generated by a separate structural renderer, not by the
Cadabra translator and never by caller-supplied stdout. The scope is deliberately
limited to structural round-trip agreement: it verifies that Cadabra parsed and
returned the same tensor factors, indices, and variance. It does not claim a
general symbolic proof or infer tensor symmetries.
"""

from __future__ import annotations

from typing import Any

from automate.ir.tensors import TensorEquation, TensorExpression, TensorProduct
from automate.tensors.cadabra_adapter import run_cadabra_script
from automate.tensors.graph_translation import graph_equation_node_to_tensor_ir, graph_node_to_tensor_ir
from automate.tensors.cadabra_translation import translate_equation, translate_expression


def _independent_index(index: Any) -> str:
    symbol = str(index.symbol)
    return f"^{{{symbol}}}" if index.position == "upper" else f"_{{{symbol}}}"


def _independent_factor(factor: Any) -> str:
    return str(factor.name) + "".join(_independent_index(i) for i in factor.indices)


def _independent_product(product: TensorProduct) -> str:
    return " ".join(_independent_factor(factor) for factor in product.factors)


def independent_structural_result(expression: TensorExpression) -> str:
    """Render expected structural text without calling the Cadabra translator."""
    if expression.products is None:
        raise ValueError("Structured tensor products are required.")
    return " + ".join(_independent_product(product) for product in expression.products)


def independent_structural_equation_result(equation: TensorEquation) -> str:
    """Render expected structural equation text independently."""
    return (
        independent_structural_result(equation.lhs)
        + " = "
        + independent_structural_result(equation.rhs)
    )


def _execution_source(translation: dict) -> str:
    source = translation["source"].rstrip()
    if not source.endswith(";"):
        raise ValueError("Translated Cadabra source must end with ';'.")
    return source[:-1] + ":\nprint(str(ex))"


def verify_translated_expression(
    expression: TensorExpression,
    *,
    sandbox_limits=None,
) -> dict:
    """Translate, execute, and compare against an internally generated independent result."""
    translation = translate_expression(expression)
    expected = independent_structural_result(expression)
    result = run_cadabra_script(
        _execution_source(translation),
        expected_output=expected,
        sandbox_limits=sandbox_limits,
        claim_fingerprint_sha256=translation["ir_fingerprint_sha256"],
        comparison_target_source="independent_renderer",
    )
    result["comparison_scope"] = "structural_tensor_round_trip"
    result["independent_result"] = expected
    return result


def verify_translated_equation(
    equation: TensorEquation,
    *,
    sandbox_limits=None,
) -> dict:
    """Translate, execute, and compare a tensor equation against an independent renderer."""
    translation = translate_equation(equation)
    expected = independent_structural_equation_result(equation)
    result = run_cadabra_script(
        _execution_source(translation),
        expected_output=expected,
        sandbox_limits=sandbox_limits,
        claim_fingerprint_sha256=translation["ir_fingerprint_sha256"],
        comparison_target_source="independent_renderer",
    )
    result["comparison_scope"] = "structural_tensor_equation_round_trip"
    result["independent_result"] = expected
    return result


def verify_graph_tensor_node_with_cadabra(graph, node_id: str, *, sandbox_limits=None) -> dict:
    """Run the complete graph -> Tensor IR -> Cadabra verification boundary."""
    expression = graph_node_to_tensor_ir(graph, node_id)
    return verify_translated_expression(expression, sandbox_limits=sandbox_limits)


def verify_graph_tensor_equation_with_cadabra(graph, node_id: str, *, sandbox_limits=None) -> dict:
    """Run the complete graph equation -> Tensor IR -> Cadabra verification boundary."""
    equation = graph_equation_node_to_tensor_ir(graph, node_id)
    return verify_translated_equation(equation, sandbox_limits=sandbox_limits)
